FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    gcc-12 g++-12 \
    python3-pip \
    git \
    && apt-get clean

# Update alternatives for gcc and g++
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

# Install Python packages
RUN pip3 install --upgrade pip
RUN pip3 install wheel packaging ninja setuptools numpy
RUN pip3 install -v -r https://raw.githubusercontent.com/vllm-project/vllm/main/requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

# Clone and install vLLM
RUN git clone https://github.com/vllm-project/vllm.git /vllm
WORKDIR /vllm
RUN VLLM_TARGET_DEVICE=cpu python3 setup.py install
 