version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db  # Persist data

  stock_price_evaluator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_price_evaluator
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
