version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data/db  # Persist data

  your_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your_service
    depends_on:
      - mongodb
    volumes:
      - .:/app  # Mount your code